
    <div class="container">
      <br><br><br>
      <hr>
      <div class="footer text-center">
        <span class="label label-primary"><?php echo CalBox::cfg('app.name'); ?></span>
      </div>
    </div>

    <div class="modal fade loading" id="loadingModal" tabindex="-1" role="dialog" data-backdrop="static">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <p class="text-center text-muted">Veuillez patienter...</p>
            <div class="progress">
              <div
                class="progress-bar progress-bar-striped active"
                role="progressbar"
                aria-valuenow="100"
                aria-valuemin="0"
                aria-valuemax="100"
                style="width: 100%">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment-with-locales.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.14.30/js/bootstrap-datetimepicker.min.js"></script>
    <script src="<?php echo $themeUrl; ?>/scripts.js"></script>

  </body>

</html>
